version: "3.2"
services:
  php:
    build: 
      context: './php/'
      args:
       PHP_VERSION: ${PHP_VERSION}
    networks:
      - backend
    volumes:
      - ./web/:/var/www/html/
      - ./vendor/:/var/www/vendor
    container_name: php
  apache:
    build:
      context: './apache/'
      args:
       APACHE_VERSION: ${APACHE_VERSION}
    depends_on:
      - php
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "80:80"
    volumes:
      - ./web/:/var/www/html/
      - ./vendor/:/var/www/vendor
    container_name: apache
  mysql:
    image: mysql:${MYSQL_VERSION:-latest}
    restart: always
    ports:
      - "3300:3300"
    volumes:
            - data:/var/lib/mysql
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root_psw
      MYSQL_DATABASE: vulnerable
      MYSQL_USER: vulnerable
      MYSQL_PASSWORD: vulnerable
    container_name: mysql

  phpmyadmin:
    links:
      - mysql
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root_psw 
      PMA_ARBITRARY: 1
      MYSQL_USERNAME: vulnerable
    networks:
      - backend

networks:
  frontend:
  backend:
volumes:
    data:
